import { chromium } from 'playwright';
const url = 'file:///projects/sandbox/shadow-couple/dist/index.html';
const browser = await chromium.launch({ args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const page = await (await browser.newContext({ viewport: { width: 844, height: 390 } })).newPage();
await page.goto(url + '?room=1-3&go&auto');
await page.waitForFunction(() => window.__game && window.__game.state === 'play', null, { timeout: 20000 });
await page.waitForTimeout(300);
console.log('active element:', await page.evaluate(() => document.activeElement?.tagName + '#' + document.activeElement?.id));
await page.keyboard.down('KeyD'); await page.waitForTimeout(600);
console.log(await page.evaluate(() => { const g = window.__game; return JSON.stringify({ keys: [...g.input.keys], ax: g.input.p[0].ax, frozen: g.frozen, mode: g.mode, single: g.input.single, bx: g.bearer.pos.x.toFixed(2), state: g.state }); }));
await page.keyboard.up('KeyD');
await browser.close();
