import { chromium } from 'playwright';
const url = 'file:///projects/sandbox/shadow-couple/dist/index.html';
const browser = await chromium.launch({ args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const mk = async (tag) => { const ctx = await browser.newContext({ viewport: { width: 844, height: 390 }, hasTouch: true }); const p = await ctx.newPage(); p.errors = []; p.on('pageerror', (e) => p.errors.push(tag + ' ' + e.message)); return p; };
const A = await mk('HOST'), B = await mk('GUEST');
await A.goto(url + '?auto'); await B.goto(url + '?auto');
await A.waitForTimeout(600);
await A.click('#goCreate'); await A.fill('#nameMe', '민준'); await A.click('#btnHost');
await A.waitForFunction(() => /^[A-Z0-9]{4}$/.test(document.querySelector('#codeShow').textContent), null, { timeout: 20000 });
const code = await A.textContent('#codeShow');
await B.click('#goJoin'); await B.fill('#codeIn', code); await B.fill('#nameJoin', '서연'); await B.click('#btnJoin');
await A.waitForFunction(() => !document.querySelector('#btnHostStart').classList.contains('hidden'), null, { timeout: 25000 });
await A.evaluate(() => { const g = window.__game; g.net.send({ t: 'start' }); g.startGame(3, false); });
await A.waitForFunction(() => window.__game.state === 'play' && window.__game.roomIdx === 3, null, { timeout: 40000 });
await B.waitForFunction(() => window.__game.roomIdx === 3, null, { timeout: 20000 });
console.log('playing 2-1; now dropping guest connection');
await B.evaluate(() => window.__game.net.conn.close());
await A.waitForFunction(() => !document.querySelector('#conn').classList.contains('hidden'), null, { timeout: 15000 });
console.log('host overlay:', await A.textContent('#connMsg'));
await A.waitForFunction(() => document.querySelector('#conn').classList.contains('hidden'), null, { timeout: 60000 });
await B.waitForFunction(() => document.querySelector('#conn').classList.contains('hidden') && window.__game.net.connected, null, { timeout: 60000 });
await A.waitForTimeout(1500);
console.log('reconnected; guest room:', await B.evaluate(() => window.__game.room?.def.id), 'guest state:', await B.evaluate(() => window.__game.state));
await B.keyboard.down('ArrowUp'); await B.waitForTimeout(800); await B.keyboard.up('ArrowUp'); await A.waitForTimeout(600);
console.log('host sees guest shade at', await A.evaluate(() => window.__game.shade.pos.toArray().map((v) => v.toFixed(2)).join(',')), 'guest local', await B.evaluate(() => window.__game.shade.pos.toArray().map((v) => v.toFixed(2)).join(',')));
console.log('ERRORS:', [...A.errors, ...B.errors].slice(0, 8).join('\n') || 'none');
await browser.close();
